### ISSUE TITLE
Pause on sleep resumes even if not paused

### ISSUE THREAD

**Issue by asfaltboy** [joaomoreno/thyme#28]
Steps to reproduce:

1. have "pause on sleep" enabled
2. Start task, and Finish task.
3. Put mac to sleep
4. Wake mac up.

Expected result: nothing.
Actual result: time start new task (from 00:00).

Probably related to [this commit](https://github.com/joaomoreno/thyme/commit/03318edfede341abeb3a374dc55884951cf6c69f).

**Comment by joaomoreno** [comment]
great catch, thanks! :+1:

**Comment by asfaltboy** [comment]
Just got the new version, nicely done :tada:
