### ISSUE TITLE
request: dont lose time across restarts/crashes

### ISSUE THREAD

**Issue by jconley** [joaomoreno/thyme#29]
most modern OSX apps now save their state when Quit, and resume when launched.
would be great if Thyme could do this also.  even better if it can survive an OS lockup/hard-restart (i.e. periodically saving the counter; vs just save on Quit)

**Comment by joaomoreno** [comment]
What does it currently do? Simply stops the timer?

**Comment by jconley** [comment]
on a clean restart it does now stop/save the timer... so that's good. (didn't think that older versions did that) - but if the system crashes (hard freeze, or you can simulate with `pkill -9 Thyme`) that data is lost.
but would be nice if it periodically saved state every minute so it could recover. would be nice it would only pause instead of stop, that way you can resume it...  i use this to track time on projects, would be really nice to be able to stop/resume multiple timers for multiple projects... but that might be exceeding what this was designed for.   will close this; consider simply as feedback.
