### ISSUE TITLE
Simple note for your current task

### ISSUE THREAD

**Issue by egslava** [joaomoreno/thyme#35]
Hi! :-)
Great timer! :-) It'd be very cool if there were a possibility to input very simple label (and preference with ability to disable this functionality) of current task.

Case:
<cmd + alt + t> - "Landing page" <enter>

**Comment by HannesDev** [comment]
+1
I totally agree. A simple note or label/tag would be super helpful.

**Comment by TimonSotiropoulos** [comment]
+1 for this as well

**Comment by ajaykarwal** [comment]
+1
This simple app is exactly what I was looking for but being able to label each time slot would make it perfect.

Don't mind if the label is added before or after the timing.

**Comment by myhau** [comment]
+1

**Comment by crowecawcaw** [comment]
+1 Love this app!

**Comment by xdrakosha** [comment]
That would be grate to have such ability.

**Comment by priyaleo** [comment]
+1 It would be great to have this feature.

**Comment by plopp** [comment]
Solved by #50 . Closing.
