### ISSUE TITLE
Many menubar items - buries Thyme icon

### ISSUE THREAD

**Issue by dajare** [joaomoreno/thyme#36]
I'm sometimes using Thyme (for which, thanks!) to time how long it takes to read aloud through a manuscript. The pause/resume function is vital. But I use LibreOffice on a little MacBook, and the menubar looks like this:

[![LibO Menubar][1t]][1]

Of course, it is actually there, as one can see using an application which takes up less space on the menubar:

[![LibO Menubar][2t]][2]

Would it be possible to have a option for using Thyme in its own window? or some other means of ensuring its icon remains accessible, no matter what else is happening on the menubar? I don't know what the possibilities might be...

Thanks!

---

**Update** And of course, I had a "Doh!" moment: I can, of course, assign hotkeys. :grin: There could still be times when it would be good to have the timer itself visible, though, so the "issue" (enhancement request?) still might have some value.

[2]: http://i.imgur.com/N28RPkC.png "There it is!"
[2t]: http://i.imgur.com/N28RPkCl.png
[1]: http://i.imgur.com/9ZmrOfp.png "Icon buried - click for full-sized"
[1t]: http://i.imgur.com/9ZmrOfpl.png

**Comment by joaomoreno** [comment]
Thanks for the time to file this and for your usage of Thyme, but I think I won't do anything about it. I do see the problem of the timer, but the hotkeys definitely solve half of the problem.

**Comment by dajare** [comment]
"Won't fix" understood! Still a great app. :+1: I'll see if there are other measures I can take to keep it "revealed" if need be.

**Comment by vemv** [comment]
One always can use Bartender anyway - most items tend to be junk. This is how mine looks like:

![image](https://user-images.githubusercontent.com/1162994/44668008-a347d480-aa1c-11e8-81fe-874e9bfbfccb.png)
