### ISSUE TITLE
Open at login

### ISSUE THREAD

**Issue by HannesDev** [joaomoreno/thyme#39]
Besides that @zvaehn added already some nice preferences in the open Pull request I'd suggest to add a checkbox that says "Open at login" and that – of course – opens Thyme automatically when you log in to the computer.

**Comment by joaomoreno** [comment]
OS X lets you do that to any application.

![image](https://cloud.githubusercontent.com/assets/22350/15887411/6dfbca2c-2d62-11e6-93c9-cf7ddd8d311c.png)

**Comment by HannesDev** [comment]
I know, that's how I did it now. However my first intention was looking at the Thyme preferences and was a bit disappointed that there is not such a checkbox. It just natural because a lot of apps have this feature in their settings already.
Maybe you're right though. The best thing of Thyme is that it is so light and simple.
