### ISSUE TITLE
Not showing in menubar in El Capitan

### ISSUE THREAD

**Issue by veebee101** [joaomoreno/thyme#40]
It was useful in previous OSX to have Thyme in menubar. Any clues about how to add this on El Capitan?

**Comment by joaomoreno** [comment]
It does show up for me. Is your menu bar maybe full?

**Comment by veebee101** [comment]
Just turned on the Mac after reinstalling Thyme and voila! Your great
little app is in the menubar at startup. Thanks again for your speedy
support and all best wishes to you.

Vee
