### ISSUE TITLE
Sign software for OS X

### ISSUE THREAD

**Issue by aykamko** [joaomoreno/thyme#41]
My work computer is provisioned to disallow OS X software from unidentified developers. Could you get Thyme officially signed? [It's pretty easy](https://successfulsoftware.net/2012/08/30/how-to-sign-your-mac-os-x-app-for-gatekeeper/), as far as I know.

Thanks for your work! I love using Thyme on my personal computer.

**Comment by joaomoreno** [comment]
I don't have an Apple Developer Connection.
