### ISSUE TITLE
Project owner

### ISSUE THREAD

**Issue by steven4354** [joaomoreno/thyme#49]
Hi! I am a long-time user and fan of Thyme. Would be happy to take over as project owner if you are still looking for one

**Comment by joaomoreno** [comment]
@steven4354 Sure! Wanna review the PRs or maybe submit a PR for an issue, as a trial?

**Comment by luc4leone** [comment]
Thyme is a great app @joaomoreno, I've tried several ones, none so easy to use and you did a great design choice of just the essential features. Congratulations! 💯

**Comment by joaomoreno** [comment]
No need to pay anything! Thanks for the kind words.
